package com.demxs.tdm.domain.business.instrument;

import com.demxs.tdm.common.persistence.TreeEntity;
import com.demxs.tdm.common.sys.entity.User;
import com.demxs.tdm.domain.business.dz.DzProjectclass;
import com.fasterxml.jackson.annotation.JsonBackReference;
import org.hibernate.validator.constraints.Length;

import java.io.Serializable;
import java.util.Date;

public class DzStorageLocation extends TreeEntity<DzStorageLocation> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.id
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.name
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.parent_id
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.parent_ids
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.create_by
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.create_date
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.update_by
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.update_date
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_STORAGE_LOCATION.state
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DZ_STORAGE_LOCATION
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public DzStorageLocation(){
        super();
    }

    public DzStorageLocation(String id){
        super(id);
    }

    @Override
    @JsonBackReference
    public DzStorageLocation getParent() {
        return parent;
    }

    @Override
    @Length(min = 0, max = 2000, message = "parent_ids长度必须介于 0 和 2000 之间")
    public void setParent(DzStorageLocation parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_STORAGE_LOCATION.id
     *
     * @return the value of DZ_STORAGE_LOCATION.id
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.id
     *
     * @param id the value for DZ_STORAGE_LOCATION.id
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_STORAGE_LOCATION.name
     *
     * @return the value of DZ_STORAGE_LOCATION.name
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    @Override
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.name
     *
     * @param name the value for DZ_STORAGE_LOCATION.name
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    @Override
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_STORAGE_LOCATION.parent_id
     *
     * @return the value of DZ_STORAGE_LOCATION.parent_id
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    @Override
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.parent_id
     *
     * @param parentId the value for DZ_STORAGE_LOCATION.parent_id
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_STORAGE_LOCATION.parent_ids
     *
     * @return the value of DZ_STORAGE_LOCATION.parent_ids
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    @Override
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.parent_ids
     *
     * @param parentIds the value for DZ_STORAGE_LOCATION.parent_ids
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    @Override
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.create_by
     *
     * @param createBy the value for DZ_STORAGE_LOCATION.create_by
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    public String getCreateBySon(){
        User createBy = super.createBy;
        if(createBy != null){
            return createBy.getId();
        }
        return "";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_STORAGE_LOCATION.create_date
     *
     * @return the value of DZ_STORAGE_LOCATION.create_date
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.create_date
     *
     * @param createDate the value for DZ_STORAGE_LOCATION.create_date
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.update_by
     *
     * @param updateBy the value for DZ_STORAGE_LOCATION.update_by
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_STORAGE_LOCATION.update_date
     *
     * @return the value of DZ_STORAGE_LOCATION.update_date
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.update_date
     *
     * @param updateDate the value for DZ_STORAGE_LOCATION.update_date
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_STORAGE_LOCATION.state
     *
     * @return the value of DZ_STORAGE_LOCATION.state
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_STORAGE_LOCATION.state
     *
     * @param state the value for DZ_STORAGE_LOCATION.state
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

}