
package com.landray.kmss.sys.notify.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-11-27T15:34:50.077+08:00
 * Generated source version: 2.4.2
 * 
 */
public final class ISysNotifyTodoWebService_ISysNotifyTodoWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.notify.sys.kmss.landray.com/", "ISysNotifyTodoWebServiceService");

    private ISysNotifyTodoWebService_ISysNotifyTodoWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ISysNotifyTodoWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ISysNotifyTodoWebServiceService ss = new ISysNotifyTodoWebServiceService(wsdlURL, SERVICE_NAME);
        ISysNotifyTodoWebService port = ss.getISysNotifyTodoWebServicePort();  
        
        {
        System.out.println("Invoking updateTodo...");
        NotifyTodoUpdateContext _updateTodo_arg0 = new NotifyTodoUpdateContext();
        try {
            NotifyTodoAppResult _updateTodo__return = port.updateTodo(_updateTodo_arg0);
            System.out.println("updateTodo.result=" + _updateTodo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setTodoDone...");
        NotifyTodoRemoveContext _setTodoDone_arg0 = new NotifyTodoRemoveContext();
        try {
            NotifyTodoAppResult _setTodoDone__return = port.setTodoDone(_setTodoDone_arg0);
            System.out.println("setTodoDone.result=" + _setTodoDone__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTodo...");
        NotifyTodoGetContext _getTodo_arg0 = new NotifyTodoGetContext();
        try {
            NotifyTodoAppResult _getTodo__return = port.getTodo(_getTodo_arg0);
            System.out.println("getTodo.result=" + _getTodo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTodoCount...");
        NotifyTodoGetCountContext _getTodoCount_arg0 = new NotifyTodoGetCountContext();
        try {
            NotifyTodoAppResult _getTodoCount__return = port.getTodoCount(_getTodoCount_arg0);
            System.out.println("getTodoCount.result=" + _getTodoCount__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendTodo...");
        NotifyTodoSendContext _sendTodo_arg0 = new NotifyTodoSendContext();
        try {
            NotifyTodoAppResult _sendTodo__return = port.sendTodo(_sendTodo_arg0);
            System.out.println("sendTodo.result=" + _sendTodo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteTodo...");
        NotifyTodoRemoveContext _deleteTodo_arg0 = new NotifyTodoRemoveContext();
        try {
            NotifyTodoAppResult _deleteTodo__return = port.deleteTodo(_deleteTodo_arg0);
            System.out.println("deleteTodo.result=" + _deleteTodo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
