package com.demxs.tdm.dao.business.instrument;

import com.demxs.tdm.common.persistence.CrudDao;
import com.demxs.tdm.common.persistence.annotation.MyBatisDao;
import com.demxs.tdm.domain.business.instrument.DzCirculationRecord;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

@MyBatisDao
public interface DzCirculationRecordDao extends CrudDao<DzCirculationRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_CIRCULATION_RECORD
     *
     * @mbggenerated Wed Apr 08 22:39:22 CST 2020
     */
    int insert(DzCirculationRecord record);

    DzCirculationRecord selectAuditInfolist(@Param("id") String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_INSTRUMENTS_APPARATUSES
     *
     * @mbggenerated Sat Apr 04 22:07:54 CST 2020
     */
    int insertSelective(DzCirculationRecord record);
//@Param("state")String state
    List<DzCirculationRecord> selectfindListLYJL1(@Param("name") String name, @Param("leader") String leader, @Param("restitution") String restitution);
    List<DzCirculationRecord> selectfindListLYJL2(@Param("name") String name, @Param("leader") String leader, @Param("restitution") String restitution);

    List<DzCirculationRecord> getRecord(@Param("relationId")  String relationId);


    List<DzCirculationRecord>  getUserName();

    List<DzCirculationRecord> getInOrOut(@Param("userName") String userName);

    List<DzCirculationRecord>  getRecordInfo(DzCirculationRecord record);

    void updateInfo(DzCirculationRecord record);

    List<DzCirculationRecord> getLendRecord(@Param("relationId") String relationId);


    List<DzCirculationRecord> getLendingRecordInfo(DzCirculationRecord record);


}