package com.demxs.tdm.domain.business.dz;

import com.demxs.tdm.common.persistence.DataEntity;

public class DzCapabilityInfo extends DataEntity<DzCapabilityInfo> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_CAPABILITY_INFO.id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_CAPABILITY_INFO.number
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_CAPABILITY_INFO.name
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_CAPABILITY_INFO.department
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_CAPABILITY_INFO.undertake_tasks
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String undertakeTasks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_CAPABILITY_INFO.settlement_price
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String settlementPrice;

    public String getRelationIds() {
        return relationIds;
    }

    public void setRelationIds(String relationIds) {
        this.relationIds = relationIds;
    }

    private String relationIds;

    public String getCapabilityId() {
        return capabilityId;
    }

    public void setCapabilityId(String capabilityId) {
        this.capabilityId = capabilityId;
    }

    private String capabilityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DZ_CAPABILITY_INFO
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_CAPABILITY_INFO.id
     *
     * @return the value of DZ_CAPABILITY_INFO.id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_CAPABILITY_INFO.id
     *
     * @param id the value for DZ_CAPABILITY_INFO.id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_CAPABILITY_INFO.number
     *
     * @return the value of DZ_CAPABILITY_INFO.number
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_CAPABILITY_INFO.number
     *
     * @param number the value for DZ_CAPABILITY_INFO.number
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_CAPABILITY_INFO.name
     *
     * @return the value of DZ_CAPABILITY_INFO.name
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_CAPABILITY_INFO.name
     *
     * @param name the value for DZ_CAPABILITY_INFO.name
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_CAPABILITY_INFO.department
     *
     * @return the value of DZ_CAPABILITY_INFO.department
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_CAPABILITY_INFO.department
     *
     * @param department the value for DZ_CAPABILITY_INFO.department
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_CAPABILITY_INFO.undertake_tasks
     *
     * @return the value of DZ_CAPABILITY_INFO.undertake_tasks
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getUndertakeTasks() {
        return undertakeTasks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_CAPABILITY_INFO.undertake_tasks
     *
     * @param undertakeTasks the value for DZ_CAPABILITY_INFO.undertake_tasks
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setUndertakeTasks(String undertakeTasks) {
        this.undertakeTasks = undertakeTasks == null ? null : undertakeTasks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_CAPABILITY_INFO.settlement_price
     *
     * @return the value of DZ_CAPABILITY_INFO.settlement_price
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_CAPABILITY_INFO.settlement_price
     *
     * @param settlementPrice the value for DZ_CAPABILITY_INFO.settlement_price
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setSettlementPrice(String settlementPrice) {
        this.settlementPrice = settlementPrice == null ? null : settlementPrice.trim();
    }
}