package com.demxs.tdm.domain.business.dz;

import com.demxs.tdm.common.persistence.DataEntity;

public class DzPorsvisile  extends DataEntity<DzPorsvisile> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PORSVISIBLE.id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PORSVISIBLE.project_id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PORSVISIBLE.system_id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    private String systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PORSVISIBLE.visibleDes
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    private String visibledes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PORSVISIBLE.visibleUes
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    private String visibleues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PORSVISIBLE.state
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DZ_PORSVISIBLE
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PORSVISIBLE.id
     *
     * @return the value of DZ_PORSVISIBLE.id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PORSVISIBLE.id
     *
     * @param id the value for DZ_PORSVISIBLE.id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PORSVISIBLE.project_id
     *
     * @return the value of DZ_PORSVISIBLE.project_id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PORSVISIBLE.project_id
     *
     * @param projectId the value for DZ_PORSVISIBLE.project_id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PORSVISIBLE.system_id
     *
     * @return the value of DZ_PORSVISIBLE.system_id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PORSVISIBLE.system_id
     *
     * @param systemId the value for DZ_PORSVISIBLE.system_id
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId == null ? null : systemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PORSVISIBLE.visibleDes
     *
     * @return the value of DZ_PORSVISIBLE.visibleDes
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public String getVisibledes() {
        return visibledes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PORSVISIBLE.visibleDes
     *
     * @param visibledes the value for DZ_PORSVISIBLE.visibleDes
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public void setVisibledes(String visibledes) {
        this.visibledes = visibledes == null ? null : visibledes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PORSVISIBLE.visibleUes
     *
     * @return the value of DZ_PORSVISIBLE.visibleUes
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public String getVisibleues() {
        return visibleues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PORSVISIBLE.visibleUes
     *
     * @param visibleues the value for DZ_PORSVISIBLE.visibleUes
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public void setVisibleues(String visibleues) {
        this.visibleues = visibleues == null ? null : visibleues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PORSVISIBLE.state
     *
     * @return the value of DZ_PORSVISIBLE.state
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PORSVISIBLE.state
     *
     * @param state the value for DZ_PORSVISIBLE.state
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}