package com.demxs.tdm.domain.business.dz;
import com.demxs.tdm.common.persistence.DataEntity;
import com.demxs.tdm.domain.business.AuditInfo;

import java.util.List;

public class DzProviderOrCapability extends DataEntity<DzProviderOrCapability> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PROVIDER_OR_CAPABILITY.id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PROVIDER_OR_CAPABILITY.provider_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String providerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PROVIDER_OR_CAPABILITY.capability_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String capabilityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PROVIDER_OR_CAPABILITY.relation_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZ_PROVIDER_OR_CAPABILITY.state
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DZ_PROVIDER_OR_CAPABILITY
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public List<AuditInfo> getAuditInfoList() {
        return this.auditInfoList = auditInfoList == null ? null : auditInfoList;
    }

    public void setAuditInfoList(List<AuditInfo> auditInfoList) {
        this.auditInfoList = auditInfoList == null ? null : auditInfoList;
    }

    private List<AuditInfo> auditInfoList;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PROVIDER_OR_CAPABILITY.id
     *
     * @return the value of DZ_PROVIDER_OR_CAPABILITY.id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PROVIDER_OR_CAPABILITY.id
     *
     * @param id the value for DZ_PROVIDER_OR_CAPABILITY.id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PROVIDER_OR_CAPABILITY.provider_id
     *
     * @return the value of DZ_PROVIDER_OR_CAPABILITY.provider_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PROVIDER_OR_CAPABILITY.provider_id
     *
     * @param providerId the value for DZ_PROVIDER_OR_CAPABILITY.provider_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setProviderId(String providerId) {
        this.providerId = providerId == null ? null : providerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PROVIDER_OR_CAPABILITY.capability_id
     *
     * @return the value of DZ_PROVIDER_OR_CAPABILITY.capability_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getCapabilityId() {
        return capabilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PROVIDER_OR_CAPABILITY.capability_id
     *
     * @param capabilityId the value for DZ_PROVIDER_OR_CAPABILITY.capability_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setCapabilityId(String capabilityId) {
        this.capabilityId = capabilityId == null ? null : capabilityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PROVIDER_OR_CAPABILITY.relation_id
     *
     * @return the value of DZ_PROVIDER_OR_CAPABILITY.relation_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PROVIDER_OR_CAPABILITY.relation_id
     *
     * @param relationId the value for DZ_PROVIDER_OR_CAPABILITY.relation_id
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId == null ? null : relationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZ_PROVIDER_OR_CAPABILITY.state
     *
     * @return the value of DZ_PROVIDER_OR_CAPABILITY.state
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZ_PROVIDER_OR_CAPABILITY.state
     *
     * @param state the value for DZ_PROVIDER_OR_CAPABILITY.state
     *
     * @mbggenerated Fri Mar 06 17:20:54 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}