package com.demxs.tdm.dao.business.dz;

import com.demxs.tdm.common.persistence.CrudDao;
import com.demxs.tdm.common.persistence.annotation.MyBatisDao;
import com.demxs.tdm.domain.business.dz.DzDevelopmentPlan;

import java.util.List;

@MyBatisDao
public interface DzDevelopmentPlanDao  extends CrudDao<DzDevelopmentPlanDao> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_DEVELOPMENT_PLAN
     *
     * @mbggenerated Thu Mar 12 15:30:17 CST 2020
     */
    int deleteByPrimaryKey(String id);
    int updatePlanning(DzDevelopmentPlan dzDevelopmentPlan);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_DEVELOPMENT_PLAN
     *
     * @mbggenerated Thu Mar 12 15:30:17 CST 2020
     */
    int insert(DzDevelopmentPlan record);

    List<DzDevelopmentPlan> getplanningfilesList(String id);

    List<DzDevelopmentPlan> getplanningfilesList2(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_DEVELOPMENT_PLAN
     *
     * @mbggenerated Thu Mar 12 15:30:17 CST 2020
     */
    int insertSelective(DzDevelopmentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_DEVELOPMENT_PLAN
     *
     * @mbggenerated Thu Mar 12 15:30:17 CST 2020
     */
    DzDevelopmentPlan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_DEVELOPMENT_PLAN
     *
     * @mbggenerated Thu Mar 12 15:30:17 CST 2020
     */
    int updateByPrimaryKeySelective(DzDevelopmentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_DEVELOPMENT_PLAN
     *
     * @mbggenerated Thu Mar 12 15:30:17 CST 2020
     */
    int updateByPrimaryKey(DzDevelopmentPlan record);
}