package com.demxs.tdm.dao.business.dz;

import com.demxs.tdm.common.persistence.CrudDao;
import com.demxs.tdm.common.persistence.annotation.MyBatisDao;
import com.demxs.tdm.domain.business.dz.DzPorsvisile;
@MyBatisDao
public interface DzPorsvisileDao extends CrudDao<DzPorsvisile>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_PORSVISIBLE
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    int delect(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_PORSVISIBLE
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    int insert(DzPorsvisile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_PORSVISIBLE
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    int insertSelective(DzPorsvisile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_PORSVISIBLE
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    DzPorsvisile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_PORSVISIBLE
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    int updateByPrimaryKeySelective(DzPorsvisile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZ_PORSVISIBLE
     *
     * @mbggenerated Wed Mar 25 11:45:59 CST 2020
     */
    int updateByPrimaryKey(DzPorsvisile record);
}